Seciovni.Web/Models/InvoiceModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Seciovni.Web.Models
{
    public class InvoiceModel
    {
    }
}

Seciovni.Web/Controllers/AccountController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.Authentication;
using Microsoft.AspNetCore.Mvc;
using Seciovni.Web.WebHelpers;
using Shared;
using Shared.SecurityTypes;
using System;
using System.Linq;
using System.Security.Claims;
using System.Text;

namespace Seciovni.Web.Controllers
{
    public class AccountController : Controller
    {
        public IActionResult AccessDenied()
        {
            return View();
        }

        public IActionResult SignIn()
        {
            return Challenge(
                new AuthenticationProperties { RedirectUri = "/" }, OpenIdConnectDefaults.AuthenticationScheme);
        }

        public IActionResult SignOut()
        {
            var callbackUrl = Url.Action("SignedOut", "Account", values: null, protocol: Request.Scheme);
            return SignOut(new AuthenticationProperties { RedirectUri = callbackUrl },
                CookieAuthenticationDefaults.AuthenticationScheme, OpenIdConnectDefaults.AuthenticationScheme);
        }

        public IActionResult SignedOut()
        {
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                // Redirect to home page if the user is authenticated.
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).Replace("Controller", ""));
            }

            return View();
        }

        [Authorize(Policy = AccessPolicy.AdminPrivilege)]
        [Authorize(Policy = AccessPolicy.EditInvoicePrivilege)]
        [Authorize(Policy = AccessPolicy.FormEditorPrivilege)]
        [Authorize(Policy = AccessPolicy.ViewInvoicePrivilege)]
        [HttpGet]
        public IActionResult GetAuthToken()
        {
            if (HttpContext.Session.Keys.Contains(Constants.AUTH_TOKEN) &&
                HttpContext.Session.Keys.Contains(Constants.AUTH_TOKEN_TIME))
            {
                byte[] ticks;

                HttpContext.Session.TryGetValue(Constants.AUTH_TOKEN_TIME, out ticks);

                DateTime expires = DateTime.FromBinary(BitConverter.ToInt64(ticks, 0));

                // If we've expired
                if (DateTime.Now - expires < TimeSpan.Zero)
                {
                    string token = ApiLogin.GetToken(User);

                    if (string.IsNullOrWhiteSpace(token)) return null;

                    // Need to login the user when a new token is generated
                    var email = User.FindFirst(ClaimTypes.Email)?.Value ?? User.Identity.Name;
                    ApiLogin.LoginUser(token, email);

                    HttpContext.Session.Set(Constants.AUTH_TOKEN, Encoding.ASCII.GetBytes(token));
                    HttpContext.Session.Set(Constants.AUTH_TOKEN_TIME, BitConverter.GetBytes(DateTime.UtcNow.AddMinutes(58).Ticks));

                    return Json(new { token = token, expires = $"{DateTime.UtcNow.AddMinutes(58)}+0" });
                }
                else
                {
                    byte[] tokenBytes;
                    string token;

                    if (HttpContext.Session.TryGetValue(Constants.AUTH_TOKEN, out tokenBytes))
                    {
                        token = Encoding.ASCII.GetString(tokenBytes);

                        return Json(new { token = token, expires = $"{expires}+0" });
                    }

                }
            }

            return null;
        }
    }
}

Seciovni.Web/Controllers/ContactsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Shared.SecurityTypes;

namespace Seciovni.Web.Controllers
{
    [Authorize(Policy = AccessPolicy.EditInvoicePrivilege)]
    public class ContactsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Seciovni.Web/Controllers/FormEditorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Shared.SecurityTypes;

namespace Seciovni.Web.Controllers
{
    [Authorize(Policy = AccessPolicy.FormEditorPrivilege)]
    public class FormEditorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Edit(string formName)
        {
            return View();
        }
    }
}

Seciovni.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Seciovni.Web.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

Seciovni.Web/Controllers/InvoiceController.cs
using Database.Tables;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Shared.SecurityTypes;
using System;

namespace Seciovni.Web.Controllers
{
    [Authorize]
    public class InvoiceController : Controller
    {
        [Authorize(Policy = AccessPolicy.EditInvoicePrivilege)]
        public IActionResult Edit(int id = -1)
        {
            ViewData["IsEdit"] = true;

            if (id == -1)
            {
                ViewData["Title"] = "New Invoice";
                return View(new Invoice()
                {
                    InvoiceID = -1,
                    InvoiceDate = DateTime.Now
                });
            }

            ViewData["Title"] = "Edit Invoice " + id.ToString("D4");
            ViewData["ShowSearch"] = true;
            return View(new Invoice()
            {
                InvoiceID = id,
            });
        }

        [Authorize(Policy = AccessPolicy.ViewInvoicePrivilege)]
        public IActionResult View(int id)
        {
            ViewData["IsEdit"] = false;

            if (id > 0)
            {
                return View(new Invoice()
                {
                    InvoiceID = id
                });
            }
            else
            {
                return View("RecentInvoices");
            }
        }
    }
}

Seciovni.Web/Controllers/ManagementController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Shared.SecurityTypes;

namespace Seciovni.Web.Controllers
{
    [Authorize(Policy = AccessPolicy.AdminPrivilege)]
    public class ManagementController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Seciovni.Web/Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;

namespace Seciovni.Web.Controllers
{
    public class SearchController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Seciovni.Web/Views/Contacts/Index.cshtml
@using Database.Tables;
@model Invoice
@{
    ViewData["title"] = "Contacts";
}

<div id="contactsPage">
    <div id="appHeader">
        <div id="leftHeader">
            <h1>Contacts</h1>
        </div>
        <div id="rightHeader">
            <button id="newButton"><img src="~/images/add.svg" /> New</button>
            <button id="saveButton"><img src="~/images/save.png" /> Save</button>
            <button id="editButton"><img src="~/images/edit.png" /> Edit</button>
            <button id="deleteButton"><img src="~/images/cancel.png" /> Delete</button>
        </div>
    </div>
    <div id="fullContactsList">
        <div id="contactMenu">
            <svg version="1.1" id="vMenu" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                 width="20px" height="20px" viewBox="0 0 20 20" style="enable-background:new 0 0 20 20;" xml:space="preserve">
            <g>
            <path fill="#4F4F4F" d="M10.001,5.352c-1.475,0-2.667-1.197-2.667-2.676C7.334,1.198,8.526,0,10.001,0
			        c1.471,0,2.665,1.197,2.665,2.676C12.665,4.153,11.472,5.352,10.001,5.352z" />
            <path fill="#4F4F4F" d="M10.001,12.676c-1.475,0-2.667-1.197-2.667-2.676c0-1.478,1.192-2.676,2.667-2.676
			        c1.471,0,2.665,1.198,2.666,2.676C12.665,11.479,11.471,12.676,10.001,12.676z" />
            <path fill="#4F4F4F" d="M10.001,20c-1.475,0-2.667-1.197-2.667-2.676s1.192-2.676,2.667-2.676
			        c1.471-0.001,2.665,1.197,2.665,2.676S11.471,20,10.001,20z" />
	        </g>
        </svg>
            <ul id="contextMenu"></ul>
        </div>
        <div id="contactSearchBar">
            <input id="contactSearchInput" type="text" placeholder="Search" />
            <div id="contactSearchButton">
                <svg version="1.1" id="magnifyingGlass" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px"
                     y="0px" width="16px" height="16px" viewBox="0 0 16 16" style="enable-background:new 0 0 16 16;" xml:space="preserve">
                <path style="fill:#4F4F4F;" d="M15.7,12.6L12,9.2c0.4-0.9,0.7-1.8,0.7-2.8C12.6,2.8,9.8,0,6.3,0C2.8,0,0,2.8,0,6.3
	                c0,3.5,2.8,6.3,6.3,6.3c1,0,2-0.2,2.8-0.7l3.5,3.8c0.3,0.4,0.9,0.4,1.3,0l1.9-1.9C16.1,13.5,16.1,13,15.7,12.6z M6.3,10.2
	                c-2.1,0-3.9-1.7-3.9-3.9s1.7-3.9,3.9-3.9c2.1,0,3.9,1.7,3.9,3.9S8.4,10.2,6.3,10.2z" />
            </svg>
            </div>
        </div>
        <div id="contactsList"></div>
    </div>
    <div id="contactView">
        <form action="#" method="post" id="contactViewForm">
            <fieldset id="cvEdit">
                <h2>Personal</h2>
                <div class="row">
                    <div class="cell subLabel halfWidth">
                        <label for="firstName" label-content="Buyer.User.FirstName"></label>
                        <input type="text" data-bind="firstName" id="firstName" />
                    </div>
                    <div class="cell subLabel halfWidth">
                        <label for="lastName" label-content="Buyer.User.LastName"></label>
                        <input type="text" data-bind="lastName" id="lastName" />
                    </div>
                </div>

                <div class="row subLabel fullWidth">
                    <label for="streetAddr" label-content="Buyer.Address.StreetAddress"></label>
                    <input id="streetAddr" data-bind="streetAddress" type="text" autocomplete="street-address" />
                </div>
                <div class="row">
                    <div class="cell subLabel">
                        <label for="city" label-content="Buyer.Address.City"></label>
                        <input id="city" data-bind="city" type="text" autocomplete="address-level2" />
                    </div>
                    <div class="cell subLabel">
                        <label for="state" label-content="Buyer.Address.State"></label>
                        <input id="state" data-bind="state" type="text" autocomplete="address-level1" />
                    </div>
                    <div class="cell subLabel">
                        <label for="zip" label-content="Buyer.Address.ZipCode"></label>
                        <input id="zip" data-bind="zipCode" type="text" autocomplete="postal-code" maxlength="5" />
                    </div>
                </div>


                <h2>Contact</h2>
                <div class="row subLabel fullWidth">
                    <label for="email" label-content="Buyer.User.Email"></label>
                    <input id="email" type="email" data-bind="email" autocomplete="email" />
                </div>
                <div class="row subLabel fullWidth">
                    <label for="pPhone" label-content="Buyer.PrimaryPhone"></label>
                    <input id="pPhone" type="tel" data-bind="primaryPhone" autocomplete="tel" />
                </div>
                <div class="row subLabel fullWidth">
                    <label for="cPhone" label-content="Buyer.CellPhone"></label>
                    <input id="cPhone" type="tel" data-bind="cellPhone" autocomplete="cell tel" />
                </div>
                <div class="row subLabel fullWidth">
                    <label for="hPhone" label-content="Buyer.HomePhone"></label>
                    <input id="hPhone" type="tel" data-bind="homePhone" autocomplete="home tel" />
                </div>
                <div class="row subLabel fullWidth">
                    <label for="wPhone" label-content="Buyer.WorkPhone"></label>
                    <input id="wPhone" type="tel" data-bind="workPhone" autocomplete="work tel" />
                </div>

                <h2>Business Information</h2>
                <div class="row subLabel fullWidth">
                    <label for="companyName" label-content="Buyer.CompanyName"></label>
                    <input id="companyName" data-bind="companyName" type="text" autocomplete="organization" />
                </div>
                <div class="row subLabel fullWidth">
                    <label for="licenseNum">Dealer License Num:</label>
                    <input id="licenseNum" data-bind="dealerLicenseNumber" type="text" />
                </div>
                <div class="row subLabel fullWidth">
                    <label for="mcNum" label-content="Buyer.MCNumber"></label>
                    <input id="mcNum" data-bind="mcNumber" type="text" />
                </div>
                <div class="row subLabel fullWidth">
                    <label for="resaleNum" label-content="Buyer.ResaleNumber"></label>
                    <input id="resaleNum" data-bind="resaleNumber" type="text" />
                </div>
            </fieldset>
        </form>
    </div>
    <div id="contactInvoices">
        <div id="invoiceList">
            <div class="header"><h2>Invoices</h2></div>
            <div><i>No Invoices</i></div>
        </div>
    </div>
</div>

<script type="text/javascript" src="~/js/Events/EventTypes/EventArgs.js"></script>
<script type="text/javascript" src="~/js/Events/EventTypes/BaseEventType.js"></script>
<script type="text/javascript" src="~/js/Events/EventTypes/PropertyChangedEventArgs.js"></script>
<script type="text/javascript" src="~/js/Events/EventTypes/DataSavedEventArgs.js"></script>
<script type="text/javascript" src="~/js/Events/EventTypes/ObjectDestroyedEventArgs.js"></script>
<script type="text/javascript" src="~/js/Events/EventTypes/MouseEvent.js"></script>
<script type="text/javascript" src="~/js/Events/EventTypes/KeyboardEvent.js"></script>

<script type="text/javascript" src="~/js/prototypes.js"></script>
<script type="text/javascript" src="~/js/search.js"></script>
<script type="text/javascript" src="~/js/Constants.js"></script>
<script type="text/javascript" src="~/js/Events/Subscribable.js"></script>
<script type="text/javascript" src="~/js/Events/SubscribableProperty.js"></script>
<script type="text/javascript" src="~/js/helpers.js"></script>
<script type="text/javascript" src="~/js/HelperTypes/HTMLElements/BaseHtmlElement.js"></script>
<script type="text/javascript" src="~/js/HelperTypes/HTMLElements/SpanElement.js"></script>
<script type="text/javascript" src="~/js/HelperTypes/HTMLElements/TextInput.js"></script>
<script type="text/javascript" src="~/js/HelperTypes/HTMLElements/NumericInput.js"></script>
<script type="text/javascript" src="~/js/Shared/User.js"></script>
<script type="text/javascript" src="~/js/Shared/Address.js"></script>
<script type="text/javascript" src="~/js/Contacts/Contact.js"></script>
<script type="text/javascript" src="~/js/Contacts/Contacts.js"></script>

Seciovni.Web/Views/FormEditor/Edit.cshtml
@using Shared;
@{
    ViewData["Title"] = "Form Editor";
    ViewData["NoContent"] = true;
}

<div id="appHeader" class="builderPageHeader">
    <div id="leftHeader">
        <div class="row">
            <label id="builderTitleLabel" for="builderTitle">Title:</label>
            <input type="text" id="builderTitle" value="Title" />
        </div>
        <div class="row">
            <label for="formState">State(s):</label>
            @foreach (InvoiceState state in Enum.GetValues(typeof(InvoiceState)))
            {
                <input type="checkbox" class="noDisplay check" id="@state.ToString()" value="@((int)state)" />
                <label for="@state.ToString()" class="checkLabel">@state.ToString()</label>
            }
        </div>
    </div>
    <div id="rightHeader">
        <a href="/FormEditor" class="button"><img src="~/images/back.svg" /> Back to Forms</a>
        <button id="saveButton"><img src="~/images/save.png" /> Save Form</button>
    </div>
</div>

<div id="formBuilder">
    <div id="builderRight">
        <div id="shapes">
            <h3>Shapes</h3>
        </div>
        <div id="properties">
            <h3>Properties</h3>
        </div>
    </div>
    <div id="builderMain">
        <div id="canvasHolder">
            <div class="spacer"></div>
            <canvas id="editor" tabindex="0"></canvas>
            <div class="spacer"></div>
        </div>
    </div>
    <div id="builderBottom">
        <div id="zoom"></div>
    </div>
</div>
<dialog id="imagePicker">
    <div id="formImages"></div>
    <div class="saveButton">
        <button>Choose Image</button>
    </div>
</dialog>

<script type="text/javascript" src="~/js/builder.js"></script>
<script type="text/javascript" src="~/js/prototypes.js"></script>
<script type="text/javascript" src="~/js/helpers.js"></script>
<script type="text/javascript" src="~/js/Constants.js"></script>
<script type="text/javascript" src="~/js/Events/EventTypes/BaseEventType.js"></script>
<script type="text/javascript" src="~/js/Events/EventTypes/KeyboardEvent.js"></script>
<script type="text/javascript" src="~/js/Events/EventTypes/MouseEvent.js"></script>
<script type="text/javascript" src="~/js/Events/EventTypes/EventArgs.js"></script>
<script type="text/javascript" src="~/js/Events/EventTypes/MouseEventArgs.js"></script>
<script type="text/javascript" src="~/js/Events/EventTypes/KeyboardEventArgs.js"></script>
<script type="text/javascript" src="~/js/Events/EventTypes/ObjectChangedEventArgs.js"></script>
<script type="text/javascript" src="~/js/Events/EventTypes/PropertyChangedEventArgs.js"></script>
<script type="text/javascript" src="~/js/Events/EventTypes/ScaleChangeEventArgs.js"></script>
<script type="text/javascript" src="~/js/FormBuilder/Statics/Keyboard.js"></script>
<script type="text/javascript" src="~/js/FormBuilder/Statics/Mouse.js"></script>
<script type="text/javascript" src="~/js/FormBuilder/Statics/HtmlTextBox.js"></script>
<script type="text/javascript" src="~/js/FormBuilder/Statics/ObjProp.js"></script>
<script type="text/javascript" src="~/js/FormBuilder/Statics/ToolTip.js"></script>
<script type="text/javascript" src="~/js/ContextMenu.js"></script>
<script type="text/javascript" src="~/js/Events/Subscribable.js"></script>
<script type="text/javascript" src="~/js/FormBuilder/Properties/BaseTypes/SubscribableProperty.js"></script>
<script type="text/javascript" src="~/js/Events/EventPropagator.js"></script>
<script type="text/javascript" src="~/js/HelperTypes/HTMLElements/BaseHtmlElement.js"></script>
<script type="text/javascript" src="~/js/HelperTypes/HTMLElements/TextInput.js"></script>
<script type="text/javascript" src="~/js/FormBuilder/FBObjects/bases/Shape.js"></script>
<script type="text/javascript" src="~/js/FormBuilder/AnchorHandle.js"></script>
<script type="text/javascript" src="~/js/FormBuilder/Properties/Appearance.js"></script>
<script type="text/javascript" src="~/js/FormBuilder/Properties/Border.js"></script>
<script type="text/javascript" src="~/js/FormBuilder/Properties/Font.js"></script>
<script type="text/javascript" src="~/js/FormBuilder/Canvas.js"></script>
<script type="text/javascript" src="~/js/FormBuilder/Properties/Caption.js"></script>
<script type="text/javascript" src="~/js/FormBuilder/Properties/Layout.js"></script>
<script type="text/javascript" src="~/js/FormBuilder/Properties/TRBL.js"></script>
<script type="text/javascript" src="~/js/FormBuilder/Binding.js"></script>
<script type="text/javascript" src="~/js/FormBuilder/FBObjects/bases/FBObject.js"></script>
<script type="text/javascript" src="~/js/FormBuilder/FBObjects/bases/TextBlock.js"></script>
<script type="text/javascript" src="~/js/FormBuilder/FBObjects/BasicShape.js"></script>
<script type="text/javascript" src="~/js/FormBuilder/FBObjects/Box.js"></script>
<script type="text/javascript" src="~/js/FormBuilder/FBObjects/Warning.js"></script>
<script type="text/javascript" src="~/js/FormBuilder/FBObjects/Ellipse.js"></script>
<script type="text/javascript" src="~/js/FormBuilder/FBObjects/Cell.js"></script>
<script type="text/javascript" src="~/js/FormBuilder/FBObjects/FBTextBlock.js"></script>
<script type="text/javascript" src="~/js/FormBuilder/FBObjects/CheckBox.js"></script>
<script type="text/javascript" src="~/js/FormBuilder/FBObjects/Table.js"></script>
<script type="text/javascript" src="~/js/FormBuilder/FBObjects/FBImage.js"></script>
<script type="text/javascript" src="~/js/FormBuilder/FormBuilder.js"></script>

<script type="text/javascript">
    const fb = new FormBuilder();
</script>

Seciovni.Web/Views/FormEditor/Index.cshtml
@{
    ViewData["Title"] = "Invoice Forms";
}

<h1>Invoice Forms</h1>

<a href="/FormEditor/Edit/" class="button"><img src="~/images/add.svg" /> Add Form</a>

<table id="formsList" class="dataTableList">
    <tr>
        <th data-column="title">Title</th>
    </tr>
</table>

<script type="text/javascript" src="~/js/Events/EventTypes/BaseEventType.js"></script>
<script type="text/javascript" src="~/js/Events/EventTypes/MouseEvent.js"></script>
<script type="text/javascript" src="~/js/Events/EventTypes/KeyboardEvent.js"></script>
<script type="text/javascript" src="~/js/helpers.js"></script>
<script type="text/javascript" src="~/js/Constants.js"></script>
<script type="text/javascript" src="~/js/prototypes.js"></script>
<script type="text/javascript" src="~/js/Events/Subscribable.js"></script>
<script type="text/javascript" src="~/js/Events/SubscribableProperty.js"></script>
<script type="text/javascript" src="~/js/HelperTypes/HTMLElements/BaseHtmlElement.js"></script>
<script type="text/javascript" src="~/js/FormBuilder/InvoiceForms.js"></script>

Seciovni.Web/Views/Home/Dashboard.cshtml
@using Shared.SecurityTypes;
@{
    ViewData["Title"] = "Dashboard";
}

<div id="dashboard">
    @*http://www.istockphoto.com/vector/file-document-icon-set-vector-eps10-gm527795151-53395100?st=86db603*@
    @if (User.HasClaim(c => c.Type == AccessPolicy.EditInvoicePrivilege || c.Type == AccessPolicy.AdminPrivilege))
    {
        <a asp-controller="Invoice" asp-action="Edit" class="dashboardButton"><p>New Invoice</p></a>
    }
    @if (User.HasClaim(c => c.Type == AccessPolicy.ViewInvoicePrivilege || c.Type == AccessPolicy.AdminPrivilege))
    { 
        <a asp-controller="Invoice" asp-action="View" class="dashboardButton"><p>View Invoices</p></a> 
    }
    @if (User.HasClaim(c => c.Type == AccessPolicy.EditInvoicePrivilege || c.Type == AccessPolicy.AdminPrivilege))
    {
        <a href="#" id="dashboardContacts" class="dashboardButton"><p>Contacts</p></a> 
    }
    @if (User.HasClaim(c => c.Type == AccessPolicy.ViewInvoicePrivilege || c.Type == AccessPolicy.AdminPrivilege))
    { 
        <a href="#" id="dashboardSearch" class="dashboardButton"><p>Search</p></a> 
    }
    @if (User.HasClaim(c => c.Type == AccessPolicy.FormEditorPrivilege || c.Type == AccessPolicy.AdminPrivilege))
    {
        <a asp-controller="FormEditor" asp-action="Edit" class="dashboardButton"><p>Form Editor</p></a>
    }
    @if (User.HasClaim(c => c.Type == AccessPolicy.AdminPrivilege)) {
        <a href="#" id="dashboardManagement" class="dashboardButton"><p>Management</p></a> 
    }
</div>

Seciovni.Web/Views/Home/Index.cshtml
@using Shared.SecurityTypes;
@{
    ViewData["Title"] = "Dashboard";
}

<div id="dashboard">
    @*http://www.istockphoto.com/vector/file-document-icon-set-vector-eps10-gm527795151-53395100?st=86db603*@
    @if (User.HasClaim(c => c.Type == AccessPolicy.EditInvoicePrivilege || c.Type == AccessPolicy.AdminPrivilege))
    {
        <a asp-controller="Invoice" asp-action="Edit" class="dashboardButton">
            <img src="~/images/new.svg" alt="" />
            <p>New Invoice</p>
        </a>
    }
    @if (User.HasClaim(c => c.Type == AccessPolicy.ViewInvoicePrivilege || c.Type == AccessPolicy.AdminPrivilege))
    { 
        <a asp-controller="Invoice" asp-action="View" class="dashboardButton">
            <img src="~/images/view.svg" alt="" id="viewShift" />
            <p>View Invoices</p>
        </a>
    }
    @if (User.HasClaim(c => c.Type == AccessPolicy.ViewInvoicePrivilege || c.Type == AccessPolicy.AdminPrivilege))
    {
        <a asp-controller="Search" asp-action="Index" class="dashboardButton">
            <img src="~/images/frontSearch.svg" alt="" />
            <p>Search Invoices</p>
        </a>
    }
    @if (User.HasClaim(c => c.Type == AccessPolicy.EditInvoicePrivilege || c.Type == AccessPolicy.AdminPrivilege))
    {
        <a asp-controller="Contacts" asp-action="Index" class="dashboardButton">
            <img src="~/images/contacts.svg" alt="" />
            <p>Contacts</p>
        </a>
    }
    @if (User.HasClaim(c => c.Type == AccessPolicy.FormEditorPrivilege || c.Type == AccessPolicy.AdminPrivilege))
    {
        <a asp-controller="FormEditor" asp-action="Index" class="dashboardButton">
            <img src="~/images/editor.svg" alt="" id="editShift" />
            <p>Form Editor</p>
        </a>
    }
    @if (User.HasClaim(c => c.Type == AccessPolicy.AdminPrivilege))
    {
        <a asp-controller="Management" asp-action="Index" class="dashboardButton">
            <img src="~/images/settings.svg" alt="" />
            <p>Management Settings</p>
        </a>
    }
</div>

Seciovni.Web/Views/Invoice/Edit.cshtml
@using Database.Tables;
@model Invoice

<div>
    @Html.Partial("InvoiceTemplate", Model)
</div>

Seciovni.Web/Views/Shared/_Menu.cshtml
<a asp-area="" asp-controller="Home" asp-action="Index" id="brand">Seciovni</a>
<ul>
    <li><a asp-area="" asp-controller="Home" asp-action="Index">Dashboard</a></li>
    @if (User.HasClaim(c => c.Type == AccessPolicy.ViewInvoicePrivilege || c.Type == AccessPolicy.AdminPrivilege))
            {
        <li><a asp-controller="Invoice" asp-action="View">Invoices</a></li>
    }
    @if (User.HasClaim(c => c.Type == AccessPolicy.FormEditorPrivilege || c.Type == AccessPolicy.AdminPrivilege))
            {
        <li><a asp-controller="FormEditor" asp-action="Index">Form Editor</a></li>
    }
</ul>
<ul id="navRight">
    @if (User.Identity.IsAuthenticated)
            {
        <li><a asp-controller="Account" asp-action="SignOut">Sign Out</a></li>
    }
    else
    {
        <li><a asp-controller="Account" asp-action="SignIn">Sign in</a></li>
    }
</ul>